"""phase1_add_organization_multi_tenancy

Revision ID: 16831d9c1a5d
Revises: 2ad815dec5d4
Create Date: 2026-02-07 18:52:32.876045
"""
from alembic import op
import sqlalchemy as sa


revision = '16831d9c1a5d'
down_revision = '2ad815dec5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', app.core.database.GUID(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('subscription_plan', sa.Enum('FREE', 'STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptionplan'), nullable=True),
    sa.Column('subscription_status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'SUSPENDED', name='subscriptionstatus'), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('max_branches', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.add_column('audit_logs', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.add_column('branches', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'branches', 'organizations', ['organization_id'], ['id'])
    op.add_column('invoices', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'organizations', ['organization_id'], ['id'])
    op.add_column('job_cards', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'job_cards', 'organizations', ['organization_id'], ['id'])
    op.add_column('notifications', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'organizations', ['organization_id'], ['id'])
    op.add_column('payments', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'payments', 'organizations', ['organization_id'], ['id'])
    op.add_column('rfqs', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'rfqs', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.add_column('vehicles', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'organizations', ['organization_id'], ['id'])
    op.add_column('work_orders', sa.Column('organization_id', app.core.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'work_orders', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'organization_id')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'organization_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.drop_column('rfqs', 'organization_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'organization_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'organization_id')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_column('job_cards', 'organization_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'organization_id')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_column('branches', 'organization_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'organization_id')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
